### ISSUE TITLE
Nav-bar hide, when reoad the page. The navbar's hide on all components

### ISSUE THREAD

**Issue by sd-chandran** [loiane/angular-login-hide-navbar#1]
I am using these way to hide the header and footer in login component. It's hiding in login component after made the changes.

But, when i am reloading the page, that time header and footer hide on all components. can anyone help to resolve these issue?

**Comment by jacckjacck** [comment]
Hi @sudhakar-sekar 

It's because the **loggedIn** variable in **AuthService** class is not persisted, it is only stored in memory, if you want to preserve the login status, you must to save, for example, in local storage and check if it exists to qualify the logged-in status.

Look at my solution:

After user login, you must store a key in local storage (maybe the token returned by the authentication server)

`localStorage.setItem('currentUserToken', JSON.stringify({token: token}));`

Then in **isLoggedIn** property (Accessor) in **AuthService** class check for local storage key

`get isLoggedIn() {

    if (localStorage.getItem('currentUserToken')) {
      this.loggedIn.next(true);
    } else {
      this.loggedIn.next(false);
    }
    return this.loggedIn.asObservable();
  }`

@loiane  thanks, an excellent post, is necessary to update the code because of the changes in angular material definitions (now all components start with **Mat** instead of **Md**)

**Comment by sd-chandran** [comment]
@jacckjacck Thanks for the response...
